puts("***Splitting a String to an array***")
puts("this is a sentence".split==["this","is","a","sentence"])
puts("***Splitting an array to a string***")
puts(["this","is","a","sentence"].join(" ")=="this is a sentence")
puts(["this","is","a","sentence"].join(", ")=="this, is, a, sentence")
